[package]
name = "demos"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "redis_demo"
path = "src/bins/redis.rs"

[[bin]]
name = "billing_demo"
path = "src/bins/billing.rs"

[[bin]]
name = "nats_demo"
path = "src/bins/nats.rs"

[dependencies]
tokio = { workspace = true }
serde_json = { workspace = true }
async-nats = { workspace = true }
futures = { workspace = true }
